backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey