backend:
  name: git-gateway
  branch: master

media_folder: "assets/images"
public_folder: "images"

collections:
  - name: "coding"
    label: "Coding"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"